### ISSUE TITLE
Unsupported URL: https://www.youtube.com/ after Update to 0.1.0

### ISSUE THREAD

**Issue by vlerenc** [synox/youtube-dl-interactive#14]
Hi, I was not longer able to use the tool and had to update it:

```   ╭────────────────────────────────────────────────╮
   │                                                │
   │        Update available 0.0.3 → 0.1.0          │
   │   Run npm i youtube-dl-interactive to update   │
   │                                                │
   ╰────────────────────────────────────────────────╯
```

I did that, but now I am getting:

```
✖ Error while loading metadata
Error: youtube-dl stopped with error:

WARNING: Falling back on generic information extractor.
ERROR: Unsupported URL: https://www.youtube.com/

    at Object.exports.getInfo (/usr/local/lib/node_modules/youtube-dl-interactive/ytdl-api.js:11:9)
    at fetchInfo (/usr/local/lib/node_modules/youtube-dl-interactive/cli.js:98:30)
    at run (/usr/local/lib/node_modules/youtube-dl-interactive/cli.js:67:11)
    at init (/usr/local/lib/node_modules/youtube-dl-interactive/cli.js:55:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/youtube-dl-interactive/cli.js:59:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)
```

What am I doing wrong? Can I go back to the previous version and switch off the update check?

**Comment by synox** [comment]
Which versions are you using?

Works for me: 

~> youtube-dl-interactive --version
0.1.0
~> youtube-dl --version
2019.07.16

And please provide a sample youtube url.

**Comment by vlerenc** [comment]
Thx, strange, indeed, works also for me. I haven't touched anything. Well, thank you anyways. Sorry bothering you.
