### ISSUE TITLE
Crashes when ran on CentOS 7

### ISSUE THREAD

**Issue by twiclo** [synox/youtube-dl-interactive#2]
```
[twiclo@toph ~]$ node --version
v6.16.0
[twiclo@toph ~]$ npm --version
3.10.10

[twiclo@toph ~]$ youtube-dl-interactive https://www.youtube.com/watch?v=VheNpiSZxf0
/usr/lib/node_modules/youtube-dl-interactive/cli.js:15
async function init(args) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
```

I ran `sudo npm install -g https://github.com/synox/youtube-dl-interactive` to install

**Comment by synox** [comment]
I think you need at least node 8. I will run some tests and document it.

**Comment by synox** [comment]
Please try again. 

    npm install -g youtube-dl-interactive

**Comment by twiclo** [comment]
I ended up updating to version 12 and it works now. Thanks
